jenkins file comented

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,74 +1,74 @@
-pipeline{
-    agent any
-    environment {
-        IMAGE_NAME = "shivammupadhyayy/frontend-app"
-        IMAGE_TAG  = "${BUID_NUMBER}"
-        APP_SERVER = "3.80.190.238"
-    }
-    stages{
-         stage('Checkout'){
-            steps{
-                git branch: 'main',
-                url: 'https://github.com/shiivamm23/Jenkins-webapp.git'
-            }
-        }
-        stage('Buid Docker Image'){
-            steps{
-                sh '''
-                docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
-                '''
-            }
-        }
-        stage('Docker Login'){
-            steps {
-                withCredentials([
-                    usernamePassword(
-                        credentialsId: 'DockerCred',
-                        usernameVariable: 'DOCKER_USER',
-                        passwordVariable: 'DOCKER_PASS'
-                    )
-                ])  {
-                    sh '''
-                    echo $DOCKER_PASS | docker login \
-                    -u $DOCKER_USER  \
-                    --password-stdin
-                    '''
-                }
-            }
-        }
-        stage('Push Image') {
-            steps {
-                sh '''
-                docker push $IMAGE_NAME:$IMAGE_TAG
-                docker tag \
-                $IMAGE_NAME:$IMAGE_TAG \
-                $IMAGE_NAME:latest
-                docker push $IMAGE_NAME:latest
-                '''
-            }
-        }
-        stage('Deploy To App Server') {
-            steps {
-                sh """
-                ssh ubuntu@$APP_SERVER '
-                docker pull $IMAGE_NAME:latest
-                docker stop frontend || true
-                docker rm frontend || true
-                docker run -d \
-                --name frontend \
-                -p 80:80 \
-                $IMAGE_NAME:latest
-                '
-                """
-            }
-        }
-    }
-    post {
-        success {
-            echo "Deployment Successful"
-        }
-        failure {
-            echo "Deployment Failed"
-        }
-    }
-}
+// pipeline{
+//     agent any
+//     environment {
+//         IMAGE_NAME = "shivammupadhyayy/frontend-app"
+//         IMAGE_TAG  = "${BUID_NUMBER}"
+//         APP_SERVER = "3.80.190.238"
+//     }
+//     stages{
+//          stage('Checkout'){
+//             steps{
+//                 git branch: 'main',
+//                 url: 'https://github.com/shiivamm23/Jenkins-webapp.git'
+//             }
+//         }
+//         stage('Buid Docker Image'){
+//             steps{
+//                 sh '''
+//                 docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+//                 '''
+//             }
+//         }
+//         stage('Docker Login'){
+//             steps {
+//                 withCredentials([
+//                     usernamePassword(
+//                         credentialsId: 'DockerCred',
+//                         usernameVariable: 'DOCKER_USER',
+//                         passwordVariable: 'DOCKER_PASS'
+//                     )
+//                 ])  {
+//                     sh '''
+//                     echo $DOCKER_PASS | docker login \
+//                     -u $DOCKER_USER  \
+//                     --password-stdin
+//                     '''
+//                 }
+//             }
+//         }
+//         stage('Push Image') {
+//             steps {
+//                 sh '''
+//                 docker push $IMAGE_NAME:$IMAGE_TAG
+//                 docker tag \
+//                 $IMAGE_NAME:$IMAGE_TAG \
+//                 $IMAGE_NAME:latest
+//                 docker push $IMAGE_NAME:latest
+//                 '''
+//             }
+//         }
+//         stage('Deploy To App Server') {
+//             steps {
+//                 sh """
+//                 ssh ubuntu@$APP_SERVER '
+//                 docker pull $IMAGE_NAME:latest
+//                 docker stop frontend || true
+//                 docker rm frontend || true
+//                 docker run -d \
+//                 --name frontend \
+//                 -p 80:80 \
+//                 $IMAGE_NAME:latest
+//                 '
+//                 """
+//             }
+//         }
+//     }
+//     post {
+//         success {
+//             echo "Deployment Successful"
+//         }
+//         failure {
+//             echo "Deployment Failed"
+//         }
+//     }
+// }
